
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./comp/headerComp/Header";
import Footer from "./comp/footer/Footer";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale} from 'next-intl/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  RootLayout({ children }) {
  const locale = await getLocale();
 
  
  return (
        <html lang={locale}>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <NextIntlClientProvider>
              <Header locale={locale} />
                  {children}
              <Footer />
            </NextIntlClientProvider>
          </body>
        </html>
  );
}
