'use client'

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./comp/headerComp/Header";
import Footer from "./comp/footer/Footer";
import useSmoothScroll from "./hooks/useSmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useSmoothScroll();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
